#!/bin/sh

###################################################################
# Script Name	: Connect monitor (conmon)
# Description	: Connets a new monitor to the right of existing one.
# Args			:
# Dependencies	: gawk, grep, xrandr, setwall
# Author		: Mateusz Reszka
# Email			: mateusz@mateuszreszka.xyz
###################################################################

defaultOutput="eDP1"
[ ! -z $DEFAULT_OUTPUT ] && defaultOutput=$DEFAULT_OUTPUT 

outputs=$(xrandr | grep -v $defaultOutput | grep -e [^s]connected | awk '{print $1}')

for output in $outputs; do
	xrandr --output $output --auto --right-of $defaultOutput
	setwall
done
