#!/bin/sh

###################################################################
# Script Name	: Current sink (currsink)
# Description	: Returns default sink.
# Args		:
# Dependencies	: pactl
# Author	: Mateusz Reszka
# Email		: mateusz@mateuszreszka.xyz
###################################################################

pactl get-default-sink
