#!/bin/sh

###################################################################
# Script Name	: mute
# Description	: Toggles mute to default sink.
# Args		:
# Dependencies	: gawk, pactl
# Variables	:
# Author	: Mateusz Reszka
# Email		: mateusz@mateuszreszka.xyz
###################################################################

sinkid=$1

[[ -z $sinkid ]] && sinkid=$(currsink);

sinkids=$(pactl list sinks short | awk -F' ' '{print $2}')

[[ "$sinkids" =~ "$sinkid" ]] &&\
    pactl set-sink-mute $sinkid toggle ||\
    echo "sink not found"; exit 2
