#!/bin/sh

sinkid=$1

[[ -z $sinkid ]] && sinkid=$(currsink);

sinkids=$(pactl list sinks short | awk -F' ' '{print $1}')

[[ "$sinkids" =~ "$sinkid" ]] &&\
    pactl set-sink-mute $sinkid toggle || echo "sink not found"; exit 2



