#!/bin/sh

###################################################################
# Script Name	: Pactl list (pl)
# Description	: Lists sinks.
# Args			:
# Dependencies	: pactl
# Author		: Mateusz Reszka
# Email			: mateusz@mateuszreszka.xyz
###################################################################

pactl list short sinks
