#!/bin/sh

###################################################################
# Script Name	: Set default sink (sds)
# Description	: Sets default sink to the provided one.
# Args		: $1 - sinkid or name
# Dependencies	: pactl
# Variables	:
# Author	: Mateusz Reszka
# Email		: mateusz@mateuszreszka.xyz
###################################################################

sink=$(pl | awk '{ print $2 }' | dmenu -i -l 6)

[ -z "$sink" ] && exit 0
pactl set-default-sink $sink

to_move=$(pactl list sink-inputs short | awk -F ' ' '{print $1}')
def_sink=$(currsink)

for i in $to_move; do
    pactl move-sink-input $i $def_sink
done
