#!/bin/sh

###################################################################
# Script Name	: Set default sink (sds)
# Description	: Sets default sink to the provided one.
# Args		: $1 - sinkid or name
# Dependencies	: pactl, switchsink
# Variables	:
# Author	: Mateusz Reszka
# Email		: mateusz@mateuszreszka.xyz
###################################################################

sink=$(pactl list short sinks | awk '{ print $2 }' | dmenu -l 6)

[ -z "$sink" ] && exit 0
pactl set-default-sink $sink
switchsink
