#!/bin/bash

if [[ -n "$(pgrep -x pulseaudio)" || -n "$(pgrep -x pipewire-pulse)" ]]; then
    curr_volume=$(pactl get-sink-volume $(currsink) | awk -F'/' '{print $2}' | tr -d ' ')
else
	curr_volume=$(amixer sget Master | grep % | awk -F"[][]" '{print $2}' | head -n 1)
fi

echo "$curr_volume"
