#!/bin/bash

###################################################################
# Script Name	: volume
# Description	: Provides info about current volume level on default sink.
# Args		:
# Dependencies	: amixer, gawk, head, pactl, pgrep, tr, currsink
# Author	: Mateusz Reszka
# Email		: mateusz@mateuszreszka.xyz
###################################################################

if [[ -n "$(pgrep -x pulseaudio)" || -n "$(pgrep -x pipewire-pulse)" ]]; then
    curr_volume=$(pactl get-sink-volume $(currsink) | awk -F'/' '{print $2}' | tr -d ' ')
else
	curr_volume=$(amixer sget Master | grep % | awk -F"[][]" '{print $2}' | head -n 1)
fi

echo "$curr_volume"
