#!/bin/bash

###################################################################
# Script Name	: volume
# Description	: Provides info about current volume level on default sink.
# Args		:
# Dependencies	: amixer, gawk, head, pactl, pgrep, tr, currsink
# Variables	:
# Author	: Mateusz Reszka
# Email		: mateusz@mateuszreszka.xyz
###################################################################

if [[ -n "$(pgrep -x pulseaudio)" || -n "$(pgrep -x pipewire-pulse)" ]]; then
    curr_volume=$(pactl get-sink-volume $(currsink) | awk 'FNR == 1 {print $5}')
else
    curr_volume=$(amixer sget Master | awk '/%/ {print $5}' | tr -d [] | head -n 1)
fi

echo "$curr_volume"
