#!/bin/sh

###################################################################
# Script Name	: Weather (weather)
# Description	: Simple script that uses openweathermap.org API_KEY to scrap current weather
# Args		: 
# Dependencies	: cat, curl, echo, find, jq, sleep
# Variables	: $OPEN_WEATHER_KEY - api key to make this work
#            	: $OPEN_WEATHER_LAT - lattitude  of the place you check weather for
#            	: $OPEN_WEATHER_LON - longtitude of the place you check weather for
# Author	: Mateusz Reszka
# Email		: mateusz@mateuszreszka.xyz
###################################################################

# latitude and longtitude scraped from there, replace {city} param to respective city:
#http://api.openweathermap.org/geo/1.0/direct?q={city}&limit=5&appid=$OPEN_WEATHER_KEY

[ -z "$OPEN_WEATHER_KEY" -o -z "$OPEN_WEATHER_LAT" -o -z "$OPEN_WEATHER_LON" ] &&\
    echo "missing api key, latitude or longtitude env var" &&\
    exit 1


call_api() {
    URL="https://api.openweathermap.org/data/3.0/onecall?units=metric&exclude=hourly,daily&lat=$OPEN_WEATHER_LAT&lon=$OPEN_WEATHER_LON&appid=$OPEN_WEATHER_KEY"
    weather=$(curl --silent --max-time 5 $URL | jq '.current.temp')
    [ -z "$weather" ] && echo "error" && exit 1
    echo "$weather" > /tmp/current_weather
}

# call api if no cached weather
[ ! -f /tmp/current_weather ] &&\
    call_api

# time in minutes
time=180

[ -n "$1" ] && time=$1

# or older than 3 hours
[ ! -n "$(find /tmp -mmin -$time 2>/dev/null | grep /tmp/current_weather)" ] &&\
    call_api

[ ! -s /tmp/current_weather ] && call_api

cat /tmp/current_weather

