#!/bin/sh

SEPARATOR=" | "

sbar=""

[ -n $LAPTOP ] && sbar+="$(sb-battery)$SEPARATOR"
sbar+="󰏔 $(sb-pacman)"
sbar+="$SEPARATOR"

weather=$(sb-weather)
[ -n "$weather" ] && sbar+="" && sbar+="$SEPARATOR"

#sbar+=" $(sb-uptime)"
#sbar+="$SEPARATOR"

sbar+=" $(sb-cpu)"
sbar+="$SEPARATOR"

sbar+=" $(sb-memory)"
sbar+="$SEPARATOR"

sbar+=" $(sb-volume)"
sbar+="$SEPARATOR"

sbar+=" $(sb-clock)"

echo $sbar
