#!/bin/sh

###################################################################
# Script Name	: Toggle touchpad (touchtog)
# Description	: Script to toggle touchpad when not needed.
#		  It finds device id and toggle it's `enable` prop.
#		  You have to change $TOUCHPAD_ID to your own.
# Args		:
# Dependencies	: xinput, gawk
# Variables	: $TOUCHPAD_ID - device id from `xinput` 
# Author	: Mateusz Reszka
# Email		: mateusz@mateuszreszka.xyz
###################################################################

deviceid=$TOUCHPAD_ID
prop=$(xinput list-props $deviceid | awk -F'[()]' '/Enabled/ {print $2}')
enabled=$(xinput list-props $deviceid | awk '/Enabled/ {print $4}')

echo $prop
echo $enabled
if [[ "$enabled" -eq "1" ]]; then
	xinput set-prop $deviceid $prop 0
	echo "touchpad off"
else
	xinput set-prop $deviceid $prop 1
	echo "touchpad on"
fi
