#!/bin/bash

###################################################################
# Script Name	: Record whole screen (recordws)
# Description	: Similar to `record` but whole screen.
# Args		: $1 - filename
# Dependencies	: wl-recorder 
# Variables	:
# Author	: Mateusz Reszka
# Email		: mateusz@mateuszreszka.xyz
###################################################################

filename=$1
[ -z "$1" ] && filename="$HOME/Videos/screencast/$(date +"%Y-%m-%dT%H-%M-%S").mp4"

wf-recorder --audio --file=$filename
