#!/bin/bash

###################################################################
# Script Name	: Record (record)
# Description	: Records section of a screen.
#		  When called second time the process gets killed, handy for a keybinding.
# Args		: $1 - filename
# Dependencies	: slop-wayland, date
# Variables	:
# Author	: Mateusz Reszka
# Email		: mateusz@mateuszreszka.xyz
###################################################################

# TODO: probably obsolete, remove it for wayland or experiment with slop on wayland branch.

filename=$1
[ -z "$1" ] && filename="$HOME/Videos/screencast/$(date +"%Y-%m-%dT%H-%M-%S").mp4"

geometry=$(slop -f "-video_size %wx%h -i :0.0+%x,%y")

wf-record --file=$filename
