#!/bin/bash

###################################################################
# Script Name	: Record (record)
# Description	: Records section of a screen.
#		  When called second time the process gets killed, handy for a keybinding.
# Args		: $1 - filename
# Dependencies	: slop-wayland, date
# Variables	:
# Author	: Mateusz Reszka
# Email		: mateusz@mateuszreszka.xyz
###################################################################

filename=$1

[ -z "$1" ] && filename="$HOME/Videos/screencast/$(date +"%Y-%m-%dT%H-%M-%S").mp4"
[ -f "$filename" ] && rm "$filename"

wf-recorder --geometry "$(slurp)" --file="$filename"
