#!/bin/bash

###################################################################
# Script Name	: Record whole screen (recordws)
# Description	: Similar to `record` but hardcoded areas.
# Args		: $1 - filename
# Dependencies	: ffmpeg 
# Variables	:
# Author	: Mateusz Reszka
# Email		: mateusz@mateuszreszka.xyz
###################################################################

filename=$1
[ -z "$1" ] && filename="$(date +"%Y-%m-%dT%H-%M-%S").mp4"

wf-recorder $filename

