#!/bin/sh

###################################################################
# Script Name	: webcam
# Description	: Uses mpv to show webcam.
# Args		: $1 - video number
# Dependencies	: mpv, v4l2
# Variables	:
# Author	: Mateusz Reszka
# Email		: mateusz@mateuszreszka.xyz
###################################################################

WEBCAM=/dev/video0

[ -n "$1" ] && WEBCAM=/dev/video$1 ||\
    WEBCAM=$(find /dev -name "video*" | grep video | dmenu -l 12)

mpv av://v4l2:$WEBCAM \
  --demuxer-lavf-o=video_size=720x540 \
  --profile=low-latency \
  --untimed \
  --quiet
