#!/bin/sh

###################################################################
# Script Name	: Light (light)
# Description	: Simple script to manage monitor brightness.
# Args			: $1 - number of percentages decrease/increase brightness, i.e. "5" or "-10"
# Dependencies	: xbacklight, cut, dunst
# Author		: Mateusz Reszka
# Email			: mateusz@mateuszreszka.xyz
###################################################################

[ -z "$1" ]  && exit 1;

[ $1 -gt 0 ] && xbacklight -inc 5
[ $1 -lt 0 ] && xbacklight -dec 5

curr_val=$(xbacklight -get | cut -d'.' -f 1)
notify-send "Light" "Light modified by $1% up to $curr_val%"

