#!/bin/sh

baseUrl="https://1337x.wtf"
input=$@

# clear file
rm /tmp/torrents.txt && touch /tmp/torrents.txt

[ -z input ] && read -p "Search movie title: " input

input=$(echo $input | tr ' ' '+')


result=$(curl -s $baseUrl/search/$input/1/ |\
  grep -Eo '\/torrent\/[0-9]{0,7}\/[A-Za-z0-9-]{0,}\/' |\
  wmenu -l 10
)

magnet=$(curl -s "$baseUrl$result" | grep -Eo '"magnet:?.*"')

mpv $magnet
