#!/bin/bash

###################################################################
# Script Name	: Record (record)
# Description	: Records screen's area provided by `slop`.
#		  When called second time the process gets killed, handy for a keybinding.
# Args		: $1 - filename
# Dependencies	: ffmpeg, dunst, slop, date
# Author	: Mateusz Reszka
# Email		: mateusz@mateuszreszka.xyz
###################################################################

( pgrep -c ffmpeg > /dev/null ) &&\
  pkill ffmpeg &&\
  notify "Recording stopped!" &&\
  exit 0

filename=$1
[ -z "$1" ] && filename="$HOME/Videos/$(date +"%Y-%m-%dT%H-%M-%S").mp4"

geometry=$(slop -f "-video_size %wx%h -i :0.0+%x,%y")

notify "Recording started!"
ffmpeg \
    -framerate 30 \
    -f x11grab $geometry \
    -pix_fmt yuv420p \
    -preset slow \
    -crf 22 \
    -c:a aac \
    -vf "pad=ceil(iw/2)*2:ceil(ih/2)*2" \
    "$filename"
