#!/bin/sh

###################################################################
# Script Name	: Repository cd (repocd)
# Description	: Lists available repositories to dmenu and changes
#		  path, if picked. Use as alias with cd or `$ cd $(repocd)`
# Args		:
# Dependencies	: find, sed, dmenu
# Author	: Mateusz Reszka
# Email		: mateusz@mateuszreszka.xyz
###################################################################

if [ ! -f /tmp/cdrepo ]; then
    touch /tmp/cdrepo
    find $REPOS/ -maxdepth 4 -type d -name .git -prune | sed "s%$REPOS%%g; s/\/\.git//g" > /tmp/cdrepo 
fi

selected=$(cat /tmp/cdrepo | dmenu -l 10)

[ -n "$selected" ] && echo $REPOS$selected


