#!/bin/sh

###################################################################
# Script Name	: SSH add key (sshadd)
# Description	: Lists ~/.ssh directory and puts it to dmenu-wl. 
#		  Makes it easier to pick an SSH key and add it to ssh-agent
# Args		:
# Dependencies	: menu, ssh, ssh-agent, ssh-add
# Variables	:
# Author	: Mateusz Reszka
# Email		: mateusz@mateuszreszka.xyz
###################################################################

# pick a key
KEY=$(ls $HOME/.ssh/ | menu)

# exit if key not picked
[ -z $KEY ] && echo "no key provided, aborting" && exit 1
echo "$HOME/.ssh/$KEY"

if [ -x /usr/bin/secret-tool ]; then 
    ssh-add $HOME/.ssh/$KEY
    exit 0
fi

ssh-add $@ "$HOME/.ssh/$KEY"

