#!/bin/sh

###################################################################
# Script Name	: Start DWM (startdwm)
# Description	: Checks if dwm has ben rebuilded lately and replaces existing instance with a new binary.
# Args		:	
# Dependencies	: sha1sum, which, dwm, sleep
# Author	: Mateusz Reszka
# Email		: mateusz@mateuszreszka.xyz
###################################################################
# relaunch DWM if the binary changes, otherwise bail

csum="x"
new_csum=$(sha1sum $(which dwm))

while true; do
    [ "$csum" != "$new_csum" ] && csum=$new_csum; dwm || exit 0
    new_csum=$(sha1sum $(which dwm))
    sleep 0.5
done
