#!/bin/sh

###################################################################
# Script Name	: Toggle touchpad (touchtog)
# Description	: Script to toggle touchpad when not needed.
#		  It finds device id and toggle it's `enable` prop.
#		  You have to change $touch_device to your own.
# Args		:
# Dependencies	: xinput, gawk, grep
# Variables	: $TOUCH_DEVICE
# Author	: Mateusz Reszka
# Email		: mateusz@mateuszreszka.xyz
###################################################################

touch_device='ALP0016'
[ -n "$TOUCH_DEVICE" ] && touch_device=$TOUCH_DEVICE

deviceid=$(xinput list | grep $touch_device | awk -F'[=[]' '{print $2}')
prop=$(xinput list-props $deviceid | grep Enabled | awk -F'[()]' '{print $2}')
enabled=$(xinput list-props $deviceid | grep Enabled | awk '{print $4}')

echo $prop
echo $enabled
if [[ "$enabled" -eq "1" ]]; then
	xinput set-prop $deviceid $prop 0
	echo "touchpad off"
else
	xinput set-prop $deviceid $prop 1
	echo "touchpad on"
fi
