#!/bin/sh

###################################################################
# Script Name	: webcam
# Description	: Uses mpv to show webcam.
# Args		:
# Dependencies	: mpv, v4l2
# Author	: Mateusz Reszka
# Email		: mateusz@mateuszreszka.xyz
###################################################################

WEBCAM=/dev/video0

mpv av://v4l2:$WEBCAM \
  --demuxer-lavf-o=video_size=720x720 \
  --profile=low-latency \
  --untimed
