#!/bin/sh

###################################################################
# Script Name	: Light (light)
# Description	: Simple script to manage monitor brightness.
# Args		: $1 - number of percentages decrease/increase brightness, i.e. "5" or "-10"
# Dependencies	: cut, dunst, brightnessctl
# Variables	:
# Author	: Mateusz Reszka
# Email		: mateusz@mateuszreszka.xyz
###################################################################

# script expects these to be called
# $ echo 'ACTION=="add", SUBSYSTEM=="backlight", RUN+="/bin/chgrp video $sys$devpath/brightness", RUN+="/bin/chmod g+w $sys$devpath/brightness"' > /etc/udev/rules.d/backlight.rules
# $ usermod -aG video [your_user]

[ -z "$1" ]  && echo "empty string" exit 1

if [ -x brightnessctl ]; then
    [ $1 -gt 0 ] && brightnessctl set +$1%
    [ $1 -lt 0 ] && brightnessctl set $1%
    perc=$(brightnessctl get | cut -d'.' -f 1)
else
    max_val=$(cat /sys/class/backlight/$BACKLIGHT_DEVICE/max_brightness)
    curr_val=$(cat /sys/class/backlight/$BACKLIGHT_DEVICE/brightness)

    new_val=$(($curr_val + (( $1 * $max_val / 100 )) ))
    [ "$new_val" -gt "$max_val" ] && new_val=$max_val

    echo $new_val > /sys/class/backlight/$BACKLIGHT_DEVICE/brightness
fi

#nots "Light" "Light modified by $1% up to $perc%"
