#!/bin/sh

###################################################################
# Script Name	: Connect monitor (moncon)
# Description	: Connets a new monitor to the right of existing one.
# Args		:
# Dependencies	: gawk, xrandr, setwall, listmon
# Variables	: $DEFAULT_OUTPUT
# Author	: Mateusz Reszka
# Email		: mateusz@mateuszreszka.xyz
###################################################################

# this is standard in laptops, that monitor will be connected all the time
defaultOutput="eDP1"
[ -n $DEFAULT_OUTPUT ] && defaultOutput=$DEFAULT_OUTPUT 

IFS='\n'

# takes all connected outputs but the default one
outputs=$(listmon | grep -v 'eDP-1')

# puts all connected outputs to right of the default one
for output in $outputs; do
	xrandr --output $output --auto --right-of $defaultOutput
	setwall
done
