#!/bin/sh

###################################################################
# Script Name	: night
# Description	: Redshift alias that stops redshift if run twice.
# Args		:
# Dependencies	: redshift
# Variables	:
# Author	: Mateusz Reszka
# Email		: mateusz@mateuszreszka.xyz
###################################################################

if [ -n "$(pgrep -x redshift)" ]; then
    nots "Night mode stopped"
    pkill redshift 
else
    nots "Night mode started"
    gammastep -l 55.7:12.6 -t 5700:2600 > /dev/null 2>&1 &
fi
