#!/bin/sh

###################################################################
# Script Name	: night
# Description	: Redshift alias that stops redshift if run twice.
# Args		:
# Dependencies	: redshift
# Author	: Mateusz Reszka
# Email		: mateusz@mateuszreszka.xyz
###################################################################

if [ -n "$(pgrep -x redshift)" ]; then
    notify-send -t 10000 "Night mode stopped"
    pkill redshift 
else
    notify-send -t 10000 "Night mode started"
    redshift -l 55.7:12.6 -t 5700:3600 -g 0.8 -m randr -v > /dev/null 2>&1 &
fi
