#!/bin/sh

###################################################################
# Script Name	: Screenshot (screenshot)
# Description	: Captures screen and saves it to clipboard
# Args		: -s: prints whole screen instead of area
# Dependencies	: convert, dunst, maim, mkdir, tee, xclip
# Variables	:
# Author	: Mateusz Reszka
# Email		: mateusz@mateuszreszka.xyz
###################################################################

# use ~/Pictures/screenshots or $SCREENSHOT_DIR if exists
dirname="$HOME/Pictures/screenshots"
[ -d $SCREENSHOT_DIR ] && dirname="$SCREENSHOT_DIR"

# make sure dir exists
mkdir -p "$dirname"

# i.e. 2022-12-31T00:01:59.png
filename="$(date --iso-8601=seconds).png"

if [ "$1" = "-s" ];then
	grim $dirname/$filename
else
	slurp | grim -g - $dirname/$filename
fi

ls $dirname/$filename | wl-copy

nots "Screenshot copied!" "Saved as:\n'$filename' at: \n '$dirname' folder"
