#!/bin/sh

###################################################################
# Script Name	: Screenshot (screenshot)
# Description	: Captures screen and saves it to clipboard
# Args		: -s: prints whole screen instead of area
# Dependencies	: convert, dunst, maim, mkdir, tee, xclip
# Author	: Mateusz Reszka
# Email		: mateusz@mateuszreszka.xyz
###################################################################

# use ~/Pictures/screenshots or $SCREENSHOT_DIR if exists
dirname="$HOME/Pictures/screenshots"
[ -d $SCREENSHOT_DIR ] && dirname="$SCREENSHOT_DIR"

# make sure dir exists
mkdir -p "$dirname"

# i.e. 2022-12-31T00:01:59.png
filename+="$(date --iso-8601=seconds).bmp"

flags="$@ --color 0,0,0,0.3 --highlight -o $dirname/$filename"

maim $flags

cat $dirname/$filename | xclip -sel clipboard -target image/png

notify-send 'Screenshot copied!' "Saved as:\n'$filename' at: \n '$dirname' folder"
