#!/bin/sh

###################################################################
# Script Name	: Screenshot (screenshot)
# Description	: Captures screen and saves it to clipboard
# Args		: -s: prints whole screen instead of area
# Dependencies	: convert, dunst, grim, slurp, mkdir, tee, wl-copy
# Variables	:
# Author	: Mateusz Reszka
# Email		: mateusz@mateuszreszka.xyz
###################################################################

[ ! -x "/usr/bin/grim" ] && notify-send "no grim installed" && exit 1
[ ! -x "/usr/bin/slurp" ] && notify-send "no slurp installed" && exit 1

# use ~/Pictures/screenshots or $SCREENSHOT_DIR if exists
dirname="$HOME/Pictures/screenshots"
[ -d $SCREENSHOT_DIR ] && dirname="$SCREENSHOT_DIR"

# make sure dir exists
mkdir -p "$dirname"

# i.e. 2022-12-31T00:01:59.png
filename+="$(date --iso-8601=seconds).png"

# screenshot
grim -g "$(slurp)" "$dirname/$filename"

# hack to make following check work
sleep 1s

[ ! -f "$dirname/$filename" ] && notify-send "grim had issues with creating a file" && exit 1

# copy screenshot to clipboard
wl-copy < "$dirname/$filename"

nots "Screenshot copied!" "Saved as:\n'$filename' at: \n '$dirname' folder"
