#!/bin/sh

###################################################################
# Script Name	: Set wallpaper (setwall)
# Description	: Script to change a wallpaper by calling feh in $1 if provided, otherwise in $WALLPAPER_DIR.
#		  and call `setwall`. If no file provided sxiv is opened to pick one.
# Args		: $1 - (optional) wallpaper directory
# Dependencies	: feh
# Variables	: $WALLPAPER_DIR
# Author	: Mateusz Reszka
# Email		: mateusz@mateuszreszka.xyz
###################################################################

[[ -f $1 ]] && feh --bg-fill $1 && exit

# fail if no such file
[[ ! -f $file ]] && exit 1 && nots "File does not exist" "$file"

# kill previous processes & trigger new swaybg instance
pkill swaybg 
bash -c "swaybg -i $file --mode fill" &
