#!/bin/sh

###################################################################
# Script Name	: Show monitors (showmonitors)
# Description	: Lists connected display output names
# Args		:
# Dependencies	: xrandr, grep, awk
# Author	: Mateusz Reszka
# Email		: mateusz@mateuszreszka.xyz
###################################################################

xrandr | awk -F+ '/ connected/ {print }'
