#!/bin/sh

###################################################################
# Script Name	: Show monitors (showmonitors)
# Description	: Lists connected display output names
# Args		:
# Dependencies	: wl-randr, grep, awk
# Author	: Mateusz Reszka
# Email		: mateusz@mateuszreszka.xyz
###################################################################

wl-randr | awk -F+ '/ connected/ {print }'
