#!/bin/sh

###################################################################
# Script Name	: Swap wallpaper (swapwall)
# Description	: Script to change a wallpaper by copying a new one to respective folder 
#		  and call `setwall`. If no file provided sxiv is opened to pick one.
# Args		: a file directory
# Dependencies	: cp, xargs, sxiv, setwall
# Variables	: $WALLPAPERS_DIR, $WALLPAPER_DIR
# Author	: Mateusz Reszka
# Email		: mateusz@mateuszreszka.xyz
###################################################################

[ -f "$1" ] && cp $1 $WALLPAPER_DIR

sxiv -tro $WALLPAPERS_DIR |\
    xargs -I{} cp -f {} $WALLPAPER_DIR &&\
    setwall
