#!/bin/sh

###################################################################
# Script Name	: Swap resolution (swapres)
# Description	: Quick way to switch between resolutions and rates.
# Args		:
# Dependencies	: dmenu-wl, gawk, tail, tr, wl-randr
# Variables	:
# Author	: Mateusz Reszka
# Email		: mateusz@mateuszreszka.xyz
###################################################################

names=$(wlr-randr --json | jq '.[].name')

# find all enabled screens
declare -a enabled_screens
for name in ${names[@]}; do
    name=$(echo $name | tr -d '"')
    enabled=$(wlr-randr --output $name | grep -q "Enabled: yes")
    [ "$?" -eq 0 ] && enabled_screens+="$name"
done

# let user pick one
monitor=$(echo $enabled_screens | menu -l 15 -p "Pick monitor")
[ -z $monitor ] && notify "No screen picked, exiting" && exit 1

output=$(wlr-randr --output $monitor --json)

nrates=$(echo $output | jq '.[].modes | length')
declare -a modes
for rate in $(seq 0 $(( $nrates - 1 )) ); do
    picked=''

    mode=$(echo "$output" | jq ".[].modes[$rate]")

    width=$(echo $mode | jq '.width')
    height=$(echo $mode | jq '.height')
    refresh=$(echo $mode | jq '.refresh')
    current=$(echo $mode | jq '.current')
    [ "$current" == "true" ] && picked='x'

    modes+="${width}x${height}@${refresh}Hz\n"
done

mode=$(printf "$modes" | menu -l 5 -p "Pick resolution")

wlr-randr --output $monitor --mode $mode

setwall
