#!/bin/sh

###################################################################
# Script Name	: Swap resolution (swapres)
# Description	: Quick way to switch between resolutions and rates.
# Args		:
# Dependencies	: dmenu, gawk, tail, tr, xrandr
# Variables	:
# Author	: Mateusz Reszka
# Email		: mateusz@mateuszreszka.xyz
###################################################################

monitor=$(
  xrandr --listmonitors |\
  tail -n +2 |\
  awk '{ print $4 }' |\
  dmenu -l 5 -p "Pick monitor"
)

# picks a subset using -v flag and p condition to print only those resolutions, that are under certain monitor
# tail -n with `+` sign tells tail to start from certain line, we skip first one as it's monitor's name not a resolution 
# another awk just removes refresh rates as not needed
record=$(
 xrandr |\
    awk -v monitor="$monitor connected" '/connected/ {p = 0}
    	$0 ~ monitor {p = 1}
        p' |\
    tail -n +2 |\
    dmenu -l 15 -p "Pick resolution"
)

rate=$(echo $record |\
    tr -d '*+' |\
    awk '{for (f=1; f<=NF; f++) { if (f >1) print $f; } }' |\
    dmenu -l 15 -p "Pick refresh rate"
)

scale=1
[ "$monitor" = "eDP-1" ] && scale=$(printf '0.5\n0.75\n1\n2' | dmenu -l 10 -p 'pick scale (the lower, the bigger): ')

resolution=$(echo $record | awk -F' ' '{print $1}')

xrandr --output $monitor --mode $resolution --rate $rate --scale $scale

setwall
