#!/bin/sh

###################################################################
# Script Name	: hibernate 
# Description	: Dumb alias to systemctl suspend
# Args		:
# Dependencies	: systemctl
# Variables	:
# Author	: Mateusz Reszka
# Email		: mateusz@mateuszreszka.xyz
###################################################################

systemctl suspend &
