#!/bin/sh

###################################################################
# Script Name	: pdf
# Description	: PDF application alias
# Args		:
# Dependencies	: xreader
# Variables	:
# Author	: Mateusz Reszka
# Email		: mateusz@mateuszreszka.xyz
###################################################################

xreader $1
