#!/bin/sh

###################################################################
# Script Name	: Emotes
# Description	: A dumb way to store icons along with their tags to make them searchable
# Args		:
# Dependencies	: wmenu, tr, xdotool 
# Variables	:
# Files used	: icons.txt
# Author	: Mateusz Reszka
# Email		: mateusz@mateuszreszka.xyz
###################################################################

# example how to add new content over vim: ctrl+v u208c
pick=$(cat $(dirname "$0")/icons.txt | wmenu -l 10)

# stop there if nothing has been picked
[ -z "$pick" ] && exit 0

# pick only first character and insert it
xdotool type $(echo "${pick%% *}")
