#!/bin/sh

###################################################################
# Script Name	: Rip Audio CD (ripaudio)
# Description	: Simple script to rip wav, add tags and encode it with flac.
# Args		:
# Dependencies	: cdda2wav, flac, ls, xargs
# Variables	: CD_DEVICE - device to use that's alternative to /dev/sr0
# Author	: Mateusz Reszka
# Email		: mateusz@mateuszreszka.xyz
###################################################################

# fallback $CD_DEVICE to /dev/sr0 
if [ -z "$CD_DEVICE" ]; then 
    # exit when not a block device
    [ ! -b /dev/sr0 ] && echo "no sr0 device, set $CD_DEVICE if it has different alias" && exit 1

    CD_DEVICE="/dev/sr0"
fi

CD_DATABASE_URL="gnudb.gnudb.org"
CD_DATABASE_PORT=80

# split audio into wav tracks, as a consequence of cddb added, adds .inf file for each wav file as well
cdda2wav -vall cddb=-1 speed=4 -paranoia paraopts=proof -B \
    cddbp-server=$CD_DATABASE_URL \
    cddbp-port=$CD_DATABASE_PORT \
    -D $CD_DEVICE

# create flac files
ls audio_*.wav | xargs -I{} flac {}

# tag flac files using .inf files
ls audio_*.flac | sed "s/.flac$//g" | xargs -I{} inftags {}.flac {}.inf

# remove no longer needed files
rm *.wav *.inf *.cd*

# send done message
notify-send -t 10000 "ripaudio" "All done!"
